ltitle: Jaime Miranda
logo: /assets/img/Jaime.jpeg
description: "Hello this is the description"
author:
  name: Jaime Miranda
  email: consulting@miranda.one
show_downloads: false
owner_url: false
# Disable button "View My GitHub Profile"
github:
  is_project_page: false
theme: jekyll-theme-minimal
