title: Jaime Miranda
logo: /assets/img/Jaime.jpeg
description: "Great site about Jekyll on GH-Pages."
author:
  name: Jaime Miranda
  email: consulting@miranda.one
show_downloads: false
owner_url: false
theme: jekyll-theme-minimal
