title: Jaime Miranda
logo: /assets/img/Jaime.jpeg
plugins:
  - jemoji

#description: "Hello this is the description"
author:
  name: Jaime Miranda
show_downloads: false
owner_url: false
# Disable button "View My GitHub Profile"
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false

navigation:
- title: Twitter
  url: https://twitter.com/MozillaReleases
- title: Team Wiki
  url: https://wiki.mozilla.org/Release_Management
- title: Release Calendar
  url: https://wiki.mozilla.org/RapidRelease/Calendar
