title: Jaime Miranda
logo: /assets/img/JaimeOval.png
description: SAP SD | ABAP | Salesforce Sales Cloud | Process Mining
plugins:
  - jemoji

author:
  name: Jaime Miranda
show_downloads: false
owner_url: false
# Disable button "View My GitHub Profile"
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
